import esbuild from 'esbuild';
import process from 'process';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const repoRoot = path.resolve(
	fileURLToPath(new URL('.', import.meta.url)),
	'..',
);

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	loader: {
		'.svg': 'text',
	},
	alias: {
		'obsidian-anki-ast-engine/anki': path.join(
			repoRoot,
			'src/anki/client.ts',
		),
		'obsidian-anki-ast-engine/config': path.join(
			repoRoot,
			'src/config/configParser.ts',
		),
		'obsidian-anki-ast-engine/sync': path.join(
			repoRoot,
			'src/syncPipeline.ts',
		),
		'obsidian-anki-ast-engine/vault': path.join(
			repoRoot,
			'src/io/vaultAdapter.ts',
		),
		'obsidian-anki-ast-engine/cardSyntax': path.join(
			repoRoot,
			'src/cardSyntax/pluginApi.ts',
		),
		'node:fs/promises': path.join(
			fileURLToPath(new URL('.', import.meta.url)),
			'shims/fs-promises.js',
		),
		'tinyglobby': path.join(
			fileURLToPath(new URL('.', import.meta.url)),
			'shims/tinyglobby.js',
		),
		'fast-glob': path.join(
			fileURLToPath(new URL('.', import.meta.url)),
			'shims/tinyglobby.js',
		),
		'katex': path.join(
			fileURLToPath(new URL('.', import.meta.url)),
			'shims/katex-stub.js',
		),
	},
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules.flatMap((m) => [m, `node:${m}`]),
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	const pluginDir = fileURLToPath(new URL('.', import.meta.url));
	const builtMainPath = path.join(pluginDir, 'main.js');
	const rootMainPath = path.join(repoRoot, 'main.js');
	if (fs.existsSync(builtMainPath)) {
		fs.copyFileSync(builtMainPath, rootMainPath);
	}
	const builtStylesPath = path.join(pluginDir, 'styles.css');
	const rootStylesPath = path.join(repoRoot, 'styles.css');
	if (fs.existsSync(builtStylesPath)) {
		fs.copyFileSync(builtStylesPath, rootStylesPath);
	}
	process.exit(0);
} else {
	await context.watch();
}
