import esbuild from 'esbuild';
import process from 'process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const repoRoot = path.resolve(
	fileURLToPath(new URL('.', import.meta.url)),
	'..',
);

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	alias: {
		'obsidian-anki-ast-engine/anki': path.join(
			repoRoot,
			'dist/anki/client.js',
		),
		'obsidian-anki-ast-engine/config': path.join(
			repoRoot,
			'dist/config/configParser.js',
		),
		'obsidian-anki-ast-engine/sync': path.join(
			repoRoot,
			'dist/syncPipeline.js',
		),
	},
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
